---
galaxy_info:
  author: "Sean Reifschneider"
  min_ansible_version: 1.4
  platforms:
   - name: Ubuntu
     versions:
      - precise
      - quantal
      - raring
      - saucy
  categories:
    - networking
    - system
dependencies: []
